#!/usr/bin/env python3
"""
Writes compose.standalone.yml: the same stack as compose.yml, but with the helper scripts and the Caddyfile embedded
in the file itself, so it can be pasted into a web UI (OpenMediaVault's Compose plugin, Portainer) with no other files
next to it. Needs Docker Compose 2.23.1 or newer.

    python scripts/make-standalone.py
"""
import re
from pathlib import Path

root = Path(__file__).resolve().parent.parent
text = (root / "compose.yml").read_text(encoding="utf-8").replace("\r\n", "\n")

EMBED = [
    # (bind-mount line in compose.yml, config name, path inside the container, source file)
    ("      - ./scripts/db-init.sh:/db-init.sh:ro\n", "db_init", "/db-init.sh", "scripts/db-init.sh"),
    ("      - ./Caddyfile:/etc/caddy/Caddyfile:ro\n", "caddyfile", "/etc/caddy/Caddyfile", "Caddyfile"),
    ("      - ./scripts/backup-loop.sh:/backup-loop.sh:ro\n", "backup_loop", "/backup-loop.sh", "scripts/backup-loop.sh"),
    ("      - ./scripts/offsite-loop.sh:/offsite-loop.sh:ro\n", "offsite_loop", "/offsite-loop.sh", "scripts/offsite-loop.sh"),
]

SERVICE_HEAD = re.compile(r"^  [a-z][a-z0-9-]*:\n", re.M)
top = ["", "configs:"]

for mount, name, target, source in EMBED:
    assert mount in text, mount
    at = text.index(mount)
    heads = [m.start() for m in SERVICE_HEAD.finditer(text)]
    start = max(h for h in heads if h < at)
    end = min([h for h in heads if h > at] + [text.index("\nnetworks:\n")])
    block = text[start:end].replace(mount, "", 1)
    block = re.sub(r"    volumes:\n(?=    \S)", "", block)  # a `volumes:` key left with nothing under it is invalid
    entry = f"    configs:\n      - source: {name}\n        target: {target}\n"
    m = re.search(r"^    networks:", block, re.M)
    block = block[: m.start()] + entry + block[m.start():]
    text = text[:start] + block + text[end:]

    body = (root / source).read_text(encoding="utf-8").replace("\r\n", "\n").rstrip("\n")
    # `$` starts a variable in Compose, so a literal dollar in an embedded script has to be written `$$`.
    body = body.replace("$", "$$")
    top.append(f"  {name}:")
    top.append("    content: |")
    top.extend(("      " + line) if line else "" for line in body.split("\n"))

out = (
    "# GENERATED by scripts/make-standalone.py from compose.yml. Do not edit by hand: edit compose.yml and regenerate.\n"
    + text.rstrip("\n") + "\n" + "\n".join(top) + "\n"
)
(root / "compose.standalone.yml").write_text(out, encoding="utf-8", newline="\n")
print("wrote compose.standalone.yml")

# OpenMediaVault variant: named volumes become bind mounts under the plugin's data path, like the other stacks there
# (CHANGE_TO_COMPOSE_DATA_PATH/<stack>/<folder>).
omv = out
for vol in ["pg_data", "redis_data", "site_media", "caddy_data", "caddy_config", "backups"]:
    omv = re.sub(rf"(      - ){vol}:", rf"\1CHANGE_TO_COMPOSE_DATA_PATH/stack/{vol}:", omv)
omv = re.sub(r"\nvolumes:\n(?:  [a-z_]+:\n)+", "\n", omv)
omv = omv.replace("# GENERATED by scripts/make-standalone.py", "# OpenMediaVault Compose plugin variant. GENERATED by scripts/make-standalone.py", 1)
(root / "compose.omv.yml").write_text(omv, encoding="utf-8", newline="\n")
print("wrote compose.omv.yml")
